/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "infix_constants.h"

namespace infix {

const infixConstants g_infix_constants;

infixConstants::infixConstants() {
}

} // namespace

