/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef infix_CONSTANTS_H
#define infix_CONSTANTS_H

#include "infix_types.h"

namespace infix {

class infixConstants {
 public:
  infixConstants();

};

extern const infixConstants g_infix_constants;

} // namespace

#endif
