// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RemoteInfixSearch.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::infix;

class RemoteInfixSearchHandler : virtual public RemoteInfixSearchIf {
 public:
  RemoteInfixSearchHandler() {
    // Your initialization goes here
  }

  int32_t ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void findMatches(std::vector<std::string> & _return, const std::string& key) {
    // Your implementation goes here
    printf("findMatches\n");
  }

  int32_t registerService(const std::string& host, const int32_t port) {
    // Your implementation goes here
    printf("registerService\n");
  }

  int32_t deregisterService(const std::string& host, const int32_t port) {
    // Your implementation goes here
    printf("deregisterService\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<RemoteInfixSearchHandler> handler(new RemoteInfixSearchHandler());
  shared_ptr<TProcessor> processor(new RemoteInfixSearchProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

